### ISSUE TITLE
Delayed /skip time and RadioBot crash

### ISSUE THREAD

**Issue by rondevous** [c0re100/RadioBot#1]
### Steps to reproduce
1. I set the vote "update_time" to any value lower than 15s.
2. Then I sent /skip and waited.
3. Vote time exceeded (song not skipped) and RadioBot crashed.

### Config
```
"vote_time": 30,
"update_time": 5,
```

**Command line error:**
```
panic: runtime error: slice bounds out of range [1:0]

goroutine 162 [running]:
github.com/c0re100/RadioBot/fb2k.PlaySelected(0xe)
  /home/c0re/RadioBot/fb2k/control.go:69 +0x692
github.com/c0re100/RadioBot/fb2k.checkNextSong(...)
  /home/c0re/RadioBot/fb2k/control.go:103
github.com/c0re100/RadioBot/fb2k.getEvent.func1.1.1(0x83)
  /home/c0re/RadioBot/fb2k/event.go:58 +0x113
created by github.com/c0re100/RadioBot/fb2k.getEvent.func1.1
  /home/c0re/RadioBot/fb2k/event.go:52 +0x4e
```

**Comment by c0re100** [comment]
`panic: runtime error: slice bounds out of range [1:0]`
Looks like no queue song in list.....
Maybe bot need check more strict.
